version: "3"
services:
  redis-cluster-net:
    image: redislabs/redismod:latest
    container_name: redis-cluster-net
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    volumes:
      - ./configs/cluster-net.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-node1:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-node1
    volumes:
      - ./configs/node1.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data:/data
    command: redis-server /usr/local/etc/redis.conf
    depends_on:
      - redis-cluster-net

  redis-node2:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-node2
    volumes:
      - ./configs/node2.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data/node2:/data
    command: redis-server /usr/local/etc/redis.conf
    depends_on:
      - redis-cluster-net

  redis-node3:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-node3
    volumes:
      - ./configs/node3.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data/node3:/data
    command: redis-server /usr/local/etc/redis.conf
    depends_on:
      - redis-cluster-net

  redis-node4:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-node4
    volumes:
      - ./configs/node4.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data/node4:/data
    command: redis-server /usr/local/etc/redis.conf
    depends_on:
      - redis-cluster-net

  redis-node5:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-node5
    volumes:
      - ./configs/node5.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data/node5:/data
    command: redis-server /usr/local/etc/redis.conf
    depends_on:
      - redis-cluster-net

  redis-node6:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-node6
    volumes:
      - ./configs/node6.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data/node6:/data
    command: redis-server /usr/local/etc/redis.conf
    depends_on:
      - redis-cluster-net

  redis-cluster-entry:
    network_mode: "service:redis-cluster-net"
    image: redislabs/redismod:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-yes --cluster-replicas 1
    depends_on:
      - redis-cluster-net
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
