version: "3"
services:
  redis-cluster:
    image: redis:latest
    container_name: redis-cluster
    ports:
      - "6300:6300"
      - "6400:6400"
      - "6500:6500"
    volumes:
      - ./cluster.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-node1:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node1
    volumes:
      - ./node1/master.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-node2:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node2
    volumes:
      - ./node2/master.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-node3:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node3
    volumes:
      - ./node3/master.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6300 127.0.0.1:6400 127.0.0.1:6500 --cluster-yes --cluster-replicas 1
    depends_on:
      - redis-cluster
      - redis-node1
      - redis-node2
      - redis-node3
