version: "3.7"

services:
  node1:
    container_name: node1
    image: redis:latest
    ports:
      - 6300:6300
    volumes:
      - ./node1/master.conf:/etc/redis/redis.conf
      - ./data/node1/master:/etc/redis/data
    command: redis-server /etc/redis/redis.conf

  node1-replica1:
    container_name: node1-replica1
    image: redis:latest
    ports:
      - 6301:6301
    volumes:
      - ./node1/replica1.conf:/etc/redis/redis.conf
      - ./data/node1/replica1:/etc/redis/data
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - node1

  node1-replica2:
    container_name: node1-replica2
    image: redis:latest
    ports:
      - 6302:6302
    volumes:
      - ./node1/replica2.conf:/etc/redis/redis.conf
      - ./data/node1/replica2:/etc/redis/data
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - node1

  node2:
    container_name: node2
    image: redis:latest
    ports:
      - 6400:6400
    volumes:
      - ./node2/master.conf:/etc/redis/redis.conf
      - ./data/node2/master:/etc/redis/data
    command: redis-server /etc/redis/redis.conf

  node2-replica1:
    container_name: node2-replica1
    image: redis:latest
    ports:
      - 6401:6401
    volumes:
      - ./node2/replica1.conf:/etc/redis/redis.conf
      - ./data/node2/replica1:/etc/redis/data
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - node2

  node2-replica2:
    container_name: node2-replica2
    image: redis:latest
    ports:
      - 6402:6402
    volumes:
      - ./node2/replica2.conf:/etc/redis/redis.conf
      - ./data/node2/replica2:/etc/redis/data
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - node2

  node3:
    container_name: node3
    image: redis:latest
    ports:
      - 6500:6500
    volumes:
      - ./node3/master.conf:/etc/redis/redis.conf
      - ./data/node3/master:/etc/redis/data
    command: redis-server /etc/redis/redis.conf

  node3-replica1:
    container_name: node3-replica1
    image: redis:latest
    ports:
      - 6501:6501
    volumes:
      - ./node3/replica1.conf:/etc/redis/redis.conf
      - ./data/node3/replica1:/etc/redis/data
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - node3

  node3-replica2:
    container_name: node3-replica2
    image: redis:latest
    ports:
      - 6502:6502
    volumes:
      - ./node3/replica2.conf:/etc/redis/redis.conf
      - ./data/node3/replica2:/etc/redis/data
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - node3
