version: "3"
services:
  redis-cluster:
    image: redis:latest
    container_name: redis-cluster
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    volumes:
      - ./cluster.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
    command: redis-server /usr/local/etc/redis.conf

  redis-node1:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node1
    volumes:
      - ./conf/node1.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data:/_data
    command: redis-server /usr/local/etc/redis.conf

  redis-node2:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node2
    volumes:
      - ./conf/node2.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
      - ./data:/_data
    command: redis-server /usr/local/etc/redis.conf

  redis-node3:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node3
    volumes:
      - ./conf/node3.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
    command: redis-server /usr/local/etc/redis.conf

  redis-node4:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node4
    volumes:
      - ./conf/node4.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
    command: redis-server /usr/local/etc/redis.conf

  redis-node5:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node5
    volumes:
      - ./conf/node5.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
    command: redis-server /usr/local/etc/redis.conf

  redis-node6:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-node6
    volumes:
      - ./conf/node6.conf:/usr/local/etc/redis.conf
      - ./logs:/redis/logs
    command: redis-server /usr/local/etc/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    image: redis:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-yes --cluster-replicas 1
    depends_on:
      - redis-cluster
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
