version: "3.7"

services:
  node1:
    container_name: node1
    image: redis:latest
    network_mode: "host"
    volumes:
      - ./node1.conf:/usr/local/etc/redis/redis.conf
      - ./data/node1:/usr/local/etc/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  node2:
    container_name: node2
    image: redis:latest
    network_mode: "host"
    volumes:
      - ./node2.conf:/usr/local/etc/redis/redis.conf
      - ./data/node2:/usr/local/etc/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  node3:
    container_name: node3
    image: redis:latest
    network_mode: "host"
    volumes:
      - ./node3.conf:/usr/local/etc/redis/redis.conf
      - ./data/node3:/usr/local/etc/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster:
    image: redis:latest
    container_name: redis-cluster
    platform: linux/unix
    command: redis-cli --cluster create 0.0.0.0:6300 0.0.0.0:6400 0.0.0.0:6500 --cluster-yes --cluster-replicas 1
    depends_on:
      - node1
      - node2
      - node3
