version: "3.9"

networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
services:
  redis-info:
    image: redis/redis-stack:latest
    container_name: redis-info
    ports:
      - 8001:8001
    command: redis-server /configs/redisinsight.conf
  redis-node1:
    image: redis/redis-stack:latest
    container_name: redis-node1
    ports:
      - 7011:6973
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.11
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /configs/node1.conf

  redis-node2:
    image: redis/redis-stack:latest
    container_name: redis-node2
    ports:
      - 7012:6973
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.12
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /configs/node2.conf

  redis-node3:
    image: redis/redis-stack:latest
    container_name: redis-node3
    ports:
      - 7013:6973
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.13
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /configs/node3.conf

  redis-node4:
    image: redis/redis-stack:latest
    container_name: redis-node4
    ports:
      - 7014:6973
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.14
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /configs/node4.conf

  redis-node5:
    image: redis/redis-stack:latest
    container_name: redis-node5
    ports:
      - 7015:6973
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.15
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /configs/node5.conf

  redis-node6:
    image: redis/redis-stack:latest
    container_name: redis-node6
    ports:
      - 7016:6973
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.16
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /configs/node6.conf

  redis-cluster-entry:
    image: redis/redis-stack:latest
    container_name: redis-cluster-entry
    networks:
      redis_cluster_net:
        ipv4_address: 172.18.0.10
    command: redis-cli -a ${REDIS_AUTH} --cluster create 172.18.0.11:6973 172.18.0.12:6973 172.18.0.13:6973 172.18.0.14:6973 172.18.0.15:6973 172.18.0.16:6973 --cluster-yes --cluster-replicas 1
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
