version: "3.9"

networks:
  redis_cluster_net:
    driver: bridge
services:
  redis-node1:
    image: redis/redis-stack:latest
    container_name: redis-node1
    ports:
      - 7001:7001
      - 17001:17001
    networks:
      - redis_cluster_net
    volumes:
      - ./configs:/usr/local/etc/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /usr/local/etc/configs/node1.conf

  redis-node2:
    image: redis/redis-stack:latest
    container_name: redis-node2
    ports:
      - 7002:7002
      - 17002:17002
    networks:
      - redis_cluster_net
    volumes:
      - ./configs:/usr/local/etc/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /usr/local/etc/configs/node2.conf

  redis-node3:
    image: redis/redis-stack:latest
    container_name: redis-node3
    ports:
      - 7003:7003
      - 17003:17003
    networks:
      - redis_cluster_net
    volumes:
      - ./configs:/usr/local/etc/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /usr/local/etc/configs/node3.conf

  redis-node4:
    image: redis/redis-stack:latest
    container_name: redis-node4
    ports:
      - 7004:7004
      - 17004:17004
    networks:
      - redis_cluster_net
    volumes:
      - ./configs:/usr/local/etc/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /usr/local/etc/configs/node4.conf

  redis-node5:
    image: redis/redis-stack:latest
    container_name: redis-node5
    ports:
      - 7005:7005
      - 17005:17005
    networks:
      - redis_cluster_net
    volumes:
      - ./configs:/usr/local/etc/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /usr/local/etc/configs/node5.conf

  redis-node6:
    image: redis/redis-stack:latest
    container_name: redis-node6
    ports:
      - 7006:7006
      - 17006:17006
    networks:
      - redis_cluster_net
    volumes:
      - ./configs:/usr/local/etc/configs
      - ./logs:/logs
      - ./data:/data
    command: redis-server /usr/local/etc/configs/node6.conf

  redis-cluster-entry:
    image: redis/redis-stack:latest
    container_name: redis-cluster-entry
    networks:
      - redis_cluster_net
    command: redis-cli -a ${REDIS_AUTH} --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-yes --cluster-replicas 1
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
