version: "3.7"

services:
  node1:
    container_name: node1
    image: redis:latest
    ports:
      - 6300:6300
    volumes:
      - ./node1.conf:/usr/local/etc/redis/redis.conf
      - ./data/node1:/usr/local/etc/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  node2:
    container_name: node2
    image: redis:latest
    ports:
      - 6400:6400
    volumes:
      - ./node2.conf:/usr/local/etc/redis/redis.conf
      - ./data/node2:/usr/local/etc/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  node3:
    container_name: node3
    image: redis:latest
    ports:
      - 6500:6500
    volumes:
      - ./node3.conf:/usr/local/etc/redis/redis.conf
      - ./data/node3:/usr/local/etc/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cli:
    image: redis:latest
    container_name: redis-cli
    platform: linux/unix
    command: redis-cli --cluster create 127.0.0.1:6300 127.0.0.1:6400 127.0.0.1:6500 --cluster-yes --cluster-replicas 1
    depends_on:
      - node1
      - node2
      - node3
